# Flutter Apps Builder Configuration
# This file allows you to customize build metadata

# Package maintainer information
maintainer:
  name: "Russell"
  contact: "npub1kg4sdvz3l4fr99n2jdz2vdxe2mpacva87hkdetv76ywacsfq5leqquw5te"

# Build options
build:
  # Clean before building
  clean: true
  
  # Which platforms to build (set to false to skip)
  platforms:
    android_apk: true
    android_aab: true
    linux_deb: true
    linux_rpm: true
    linux_appimage: true
    linux_zip: true
    web: true

# Linux specific options
linux:
  # Desktop entry categories
  categories: "Office;Utility;"
